backend:
  name: git-gateway # Git-based backend for Netlify CMS
  branch: main # The branch to update (default is master)

media_folder: "./static/images" # Le chemin local o√π les images sont stock√©es pendant l'√©dition
public_folder: "/images" # Public URL path for images

collections:
  - name: "boats"
    label: "Bateaux"
    editor:
      preview: false
    format: "json"
    extension: "json"
    identifier_field: "model"
    summary: "{{name}}"
    description: "G√©rez la liste des bateaux affich√©s sur le site."
    file: "_data/boats.json"
    create: true
    fields:
      - label: "Bateaux"
        name: "boats"
        widget: "list"
        path: "boats"  # üî• Indique √† Decap CMS o√π se trouvent les bateaux dans le JSON
        fields:
          - { label: "Mod√®le", name: "model", widget: "string" }
          - { label: "Nom", name: "name", widget: "string" }
          - { label: "Prix", name: "price", widget: "string" }
          - { label: "Moteur", name: "engine", widget: "string" }
          - { label: "Nombre de passagers", name: "passengersNumber", widget: "string" }
          - { label: "ID du carousel", name: "carousel", widget: "string" }
          - { label: "Texte alternatif de l‚Äôimage", name: "imageAlt", widget: "string" }




